# DKMS wrapper Makefile for snd-usb-audio (volume fix)
# Called by DKMS from the source directory.
# The source directory contains a patched snapshot of sound/usb/.

KERNELRELEASE ?= $(shell uname -r)
KERNEL_HEADERS := /lib/modules/$(KERNELRELEASE)/build

all:
	$(MAKE) -C $(KERNEL_HEADERS) M=$(PWD) CONFIG_SND_USB_AUDIO=m modules

clean:
	$(MAKE) -C $(KERNEL_HEADERS) M=$(PWD) clean
